### ISSUE TITLE
Wrong file path for for output_keys json read

### ISSUE THREAD

**Issue by fusmatrs** [ScepticalRabbit/mooseherder#23]
Running an example with n_moose = 4, 12 parameter variations, run parallel. Afterthe second `run_para` call the output json file is `output-keys-13.json` but the herd `read_para()` is still trying to read `output-keys-1.json`. Will investigate.

**Comment by fusmatrs** [comment]
for reference:

`Traceback (most recent call last):
  File "/home/rspencer/pyfemop/examples/ex1_elastic_modulus_opt.py", line 69, in <module>
    mor.run(5)
  File "/home/rspencer/pyfemop/src/pyfemop/optimizationmanager/optimizationmanager.py", line 145, in run
    data_list = self._herd.read_results_para(vars_to_read)
  File "/home/rspencer/mooseherder/src/mooseherder/mooseherd.py", line 486, in read_results_para
    self._start_read(sweep_iter)      
  File "/home/rspencer/mooseherder/src/mooseherder/mooseherd.py", line 523, in _start_read
    self.read_all_output_keys()
  File "/home/rspencer/mooseherder/src/mooseherder/mooseherd.py", line 406, in read_all_output_keys
    output_files = output_files + self.read_output_key(kk+1)
  File "/home/rspencer/mooseherder/src/mooseherder/mooseherd.py", line 374, in read_output_key
    with open(self.get_output_key_file(sweep_iter)) as okf:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rspencer/pyfemop/examples/moose-workdir-1/output-key-1.json'`

**Comment by fusmatrs** [comment]
Focussing on the example 4b code. Narrowed down to read issue. If you don't read then then `output-keys-1.json` and `output-keys-2.json` are created as expected. When read is called, `output-keys-1.json` and `output-keys-9.json` are created
